[package]
edition = "2021"
name = "stm32l071_templates"
version = "0.1.0"

[dependencies]
cortex-m = { version = "0.7.7", features = [
    "inline-asm",
    "critical-section-single-core",
] }
cortex-m-rt = { version = "0.7.5", features = ["set-vtor"]}
embassy-futures = "0.1.1"
embassy-stm32 = { version = "0.2.0", features = [
    "stm32l071c8",
    "unstable-pac",
    "time-driver-any"
] }
embassy-time = { version = "0.4.0", features = ["tick-hz-1_024", "generic-queue-8"] }
panic-halt = "1.0.0"
embedded-io = { version = "0.6.1" }
embedded-hal = "1.0.0"
ufmt = "0.2.0"
heapless = { version = "0.8.0", features = ["ufmt"] }

[[bin]]
name = "hello"
path = "src/bin/hello.rs"
test = false
bench = false

[profile.dev]
debug = true
lto = true
opt-level = "z"
incremental = true

[profile.release]
# note: debug = true is okay - debuginfo isn't flashed to the device!
# in fact, after disabling it the binary size could be somehow larger
debug = true
lto = "fat"
# set to true to save some more space, don't enable when using defmt
strip = false
codegen-units = 1 # Allows LLVM to perform better optimization.
opt-level = "z" # sometimes s is better, sometimes z, test every time for the best size
incremental = true # don't disable, the size is smaller with it

